--- 
- hosts: localhost
  become: true
  tasks:  
    - 
      name: Creating k8s deployment
      command: kubectl apply -f /var/lib/jenkins/workspace/docker-k8s-app/samplewebappdeployment.yaml
      become_user: jenkins
