--- 
- hosts: localhost
  become: true
  vars:
    build_number: "{{BUILD_NUMBER}}"
  tasks:  
    - 
      name: Creating k8s deployment
      command: kubectl apply -f /var/lib/jenkins/workspace/sample-ansible-docker/samplewebappdeployment.yaml
      become_user: jenkins
