--- 
- hosts: localhost
  connection: local
  become: true
  tasks:  
    - 
      name: Creating k8s deployment
      command: kubectl apply -f samplewebappdeployment.yaml
      become_user: jenkins
