apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplewebappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samplewebapp
  template:
    metadata:
      name: samplewebapppod
      labels:
        app: samplewebapp
    spec:
      containers:
        - name: samplewebappcontainer
          image: "lekkalaramana/sample-web-application:18"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: samplewebappsvc
spec:
  selector:
    app: samplewebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
