apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplewebappdeployment
spec:
  revisionHistoryLimit: 10
  replicas: 2
  selector:
    matchLabels:
      app: samplewebapp
  template:
    metadata:
      name: samplewebapppod
      labels:
        app: samplewebapp
    spec:
      containers:
        - name: samplewebappcontainer
          image: lekkalaramana/sample-web-application:{{BUILD_NUMBER}}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: samplewebappsvc
spec:
  selector:
    app: samplewebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
